\set ON_ERROR_STOP on

SELECT CASE
         WHEN current_database() = 'sd_beg_050_t01' THEN 'true'
         ELSE 'false'
       END AS safe_database \gset

\if :safe_database
  \echo 'SCHEMA_TARGET database=sd_beg_050_t01 schema=sd_beg_050_t01'
\else
  \echo 'REFUSING_SCHEMA_LOAD expected database sd_beg_050_t01'
  \quit 3
\endif

DROP SCHEMA IF EXISTS sd_beg_050_t01 CASCADE;
CREATE SCHEMA sd_beg_050_t01;
SET search_path TO sd_beg_050_t01, pg_catalog;

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT app_user_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT app_user_email_nonempty CHECK (length(trim(email)) > 3)
);

CREATE TABLE profile (
    user_id bigint PRIMARY KEY
        REFERENCES app_user(id) ON DELETE CASCADE,
    display_name text NOT NULL,
    bio text,
    CONSTRAINT profile_display_name_nonempty
        CHECK (length(trim(display_name)) BETWEEN 1 AND 80)
);

CREATE TABLE post (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id bigint NOT NULL
        REFERENCES app_user(id) ON DELETE CASCADE,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT post_body_nonempty CHECK (length(trim(body)) BETWEEN 1 AND 5000)
);

CREATE INDEX post_author_created_idx
    ON post (author_id, created_at DESC);

CREATE TABLE profile_photo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL
        REFERENCES app_user(id) ON DELETE CASCADE,
    object_key text NOT NULL UNIQUE,
    is_current boolean NOT NULL DEFAULT false,
    CONSTRAINT profile_photo_object_key_nonempty CHECK (length(trim(object_key)) > 0)
);

CREATE INDEX profile_photo_user_idx ON profile_photo (user_id);
CREATE UNIQUE INDEX profile_photo_one_current_per_user_idx
    ON profile_photo (user_id)
    WHERE is_current;

CREATE TABLE follow (
    follower_id bigint NOT NULL
        REFERENCES app_user(id) ON DELETE CASCADE,
    followed_id bigint NOT NULL
        REFERENCES app_user(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (follower_id, followed_id),
    CONSTRAINT follow_not_self CHECK (follower_id <> followed_id)
);

CREATE INDEX follow_followed_idx ON follow (followed_id, follower_id);

COMMENT ON SCHEMA sd_beg_050_t01 IS
    'Disposable synthetic schema for SD-BEG-050-T01';
